// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqaoceedhlrawcmjqgxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxYW9jZWVkaGxyYXdjbWpxZ3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzY2MzUsImV4cCI6MjA2Mzg1MjYzNX0.RX4QU6ABVY8ovF-iz8TBd7fl-ijuaBW6vgFCKuj_d-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);